# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data
# collections: null

# Handling Reading
#safe:         false
#include:      [".htaccess"]
#exclude:      []
#keep_files:   [".git", ".svn"]
#encoding:     "utf-8"
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Conversion
markdown:    kramdown
#highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Outputting
permalink:     /:title.html
paginate:      5
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style


include: ['_pages']

prose:
  rooturl: '_posts'
  metadata:
    _posts: 
      - name: layout
        field:
          element: hidden
          value: inner
      - name: date 
        field:
          element: text
          label: Fecha de la Publicación
          value: CURRENT_DATETIME
      - name: ref
        field:
          element: text
          label: Referencia
          placeholder: Etiqueta de referencia al articulo publicado
      - name: lang
        field:
          element: multiselect
          label: Escoja el Lenguaje de su Publicación
          help: Puede ser Español e Ingles
          alterable: true
          options:
            - name: Español
              value: es 
            - name: Ingles
              value: en
      - name: categories
        field:
          element: select
          label: Escoja la categoría de su Publicación
          options:
            - name: Anuncios
              value: "- Anuncios"
            - name: Productos
              value: "- Productos"
      - name: tags
        field:
          element: multiselect
          label: Escoja la(s) etiquetas de su Publicación
          help: Puede escojer una o mas etiquetas
          alterable: true 
      - name: local_featured_image
        field:
          element: text
          label: Ingrese la imagen de su Publicación
          placeholder: Nombre del archivo.jpg o png etc...
      - name: author
        field:
          element: text
          label: Ingrese el nombre del autor
          placeholder: Nombre y apellido 
      - name: author_pic
        field:
          element: text
          label: Ingrese la imagen para el Autor de la Publicación
          placeholder: Nombre del archivo.jpg o png etc...   
      - name: author_email
        field:
          element: text
          label: Ingrese el correo electronico del Autor de la Publicación
          placeholder: algo@synergy-gb.com
      - name: lead_text
        field:
          element: text
          label: Ingrese una Pequeña Descripción de su Publicacion 
          placeholder: Corta Descripción